config/routes.rb
Aleman::Application.routes.draw do

  root :to => "play#start"
  get "/play/start" => 'play#start', :as => 'play'
  post "/play/validation" => 'play#validation', :as => 'validation'

  get "/play/next" => 'play#start', :as => 'next'
  get "/play/finish" => 'play#finish', :as => 'finish'

  resources :nouns

end

app/models/noun.rb
class Noun < ActiveRecord::Base
  validates_presence_of :article
  validates_presence_of :word
  validates_presence_of :translation
  validates_presence_of :plural

  validates_uniqueness_of :word


  # random fuctionality snippet
  def self.find(*args)
    if args.first.to_s == "random"
        sql = "SELECT id FROM nouns"

        if args.second.is_a?(Array)
             sql << " where id NOT IN (" + args.second.join(",") + ")"     if args.second.length
         end
      ids = connection.select_all(sql)
        puts sql
      super(ids[rand(ids.length)]["id"].to_i)
    else
      super
    end
  end
  # end of random snippet

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/nouns_controller.rb
class NounsController < ApplicationController

  # GET /nouns/play
  #start -> muestra el primero
  #validar -> valida resultado, pulsar en "NEXT"
  #Next -> busca otro que no haya salido y muestra el layout de "start"
  #finish -> mostramos estadisticas de resultados y reseteamos






  # GET /nouns
  # GET /nouns.xml
  def index
    @nouns = Noun.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @nouns }
    end
  end

  # GET /nouns/1
  # GET /nouns/1.xml
  def show
    @noun = Noun.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @noun }
    end
  end

  # GET /nouns/new
  # GET /nouns/new.xml
  def new
    @noun = Noun.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @noun }
    end
  end

  # GET /nouns/1/edit
  def edit
    @noun = Noun.find(params[:id])
  end

  # POST /nouns
  # POST /nouns.xml
  def create
    @noun = Noun.new(params[:noun])

    respond_to do |format|
      if @noun.save
        format.html { redirect_to(@noun, :notice => 'Noun was successfully created.') }
        format.xml  { render :xml => @noun, :status => :created, :location => @noun }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @noun.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /nouns/1
  # PUT /nouns/1.xml
  def update
    @noun = Noun.find(params[:id])

    respond_to do |format|
      if @noun.update_attributes(params[:noun])
        format.html { redirect_to(@noun, :notice => 'Noun was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @noun.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /nouns/1
  # DELETE /nouns/1.xml
  def destroy
    @noun = Noun.find(params[:id])
    @noun.destroy

    respond_to do |format|
      format.html { redirect_to(nouns_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/play_controller.rb
class PlayController < ApplicationController

 def start
    #session[:hits_translation] = 0
    #@translations = []
    #@hits_translation = session[:hits_translation]

    @hits_article = Get_hits_article()
    play_list = Get_play_list()
    @nouns_played = play_list.length - 1

    unless @nouns_played == Noun.count
      @noun = Noun.find(:random, play_list)              #obtenemos la palabra a mostrar, pasando la lista
      #@translations = get_random_translations(@noun)
      Push_play_list(@noun.id)
      respond_to do |format|
        format.html # start.html.erb
      end
    else
      redirect_to :action => 'finish'
    end
  end


    def validation
      #validamos resultado
      article_f = params[:commit]     #articulo seleccionado
      article = params[:article]

      #translation_f = params[:translation_f]        #traducción seleccionada
      #translate = params[:translate]

      @hit_article = 0
      #@hit_translation = 0

      @word_hit = article.to_s + " " + params[:word].to_s

      if article_f.downcase == article.downcase
        Push_hits_article()
        @hit_article = 1
      end
    end

   def finish
     #mostrar resumen
     @hits_article = Get_hits_article()
     #@hits_translation = session[:hits_translation]
     @nouns_played = Get_play_list().length - 1

     reset_session

     respond_to do |format|
       format.html # finish.html.erb
     end
   end

  def Get_play_list
   session[:play_list].nil? ? [0] : session[:play_list]
  end

 def Push_play_list(id)
    session[:play_list] = [0] if session[:play_list].nil?
    session[:play_list] = session[:play_list].push(id)
 end

 def Get_hits_article
   session[:hits_article].nil? ? 0 : session[:hits_article]
 end

 def Push_hits_article
    session[:hits_article] = 0 if session[:hits_article].nil?
    session[:hits_article] = session[:hits_article]+1
 end


  def get_random_translations (first_noun)
    translations = []
    translation_list = []

      translations.push(first_noun.translation)    #guardamos su traducción y buscamos otras 2 mas
      translation_list.push(first_noun.id)

      if Noun.count > 1
          noun_aux = Noun.find(:random, translation_list)   #segunda traducción
          translations.push(noun_aux.translation)
          translation_list.push(noun_aux.id)
      else
          translations.push("X")
      end

      if Noun.count > 2
          noun_aux = Noun.find(:random, translation_list)   #tercera traducción
          translations.push(noun_aux.translation)
      else
           translations.push("Y")
       end

      return translations.shuffle!                         #revolvemos!
  end
end

      #if translation_f == translate
        #session[:hits_translation] = session[:hits_translation] + 1
        #@hit_translation = 1
      #end
      #@hits_translation = session[:hits_translation]

      #play_list = session[:play_list]
      #play_list = [] if play_list.nil?
      #@nouns_played = play_list.length

      #unless play_list.length == Noun.count
      #  @noun = Noun.find(:random, play_list)
      #  #@translations = []
      #  #@translations = get_random_translations(@noun)
      #  session[:play_list] = play_list.push(@noun.id)
      #  @data = session[:play_list]
      #  render 'start'
      #else
        #flash[:notice] = "No quedan palabras para jugar"
      #  redirect_to :action => 'finish'
      #end
    #end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nouns_helper.rb
module NounsHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aleman</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/layouts/play.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Practica aleman facilmente</title>
  <%= stylesheet_link_tag "scaffold.css" %>
  <%= javascript_include_tag :defaults %>
   <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
  <%= csrf_meta_tag %>
</head>
<body>


<div id="topPan"> <%= link_to image_tag("logo.gif", :size => "208x58", :alt => "Practicar alemán facilmente", :border => "0"), root_path    %>
  <ul>
    <li class="home">Home</li>
    <% if session[:play_list].nil? %>
        <li><%= link_to 'Jugar',play_path, :class => 'home' %></li>
    <% else %>
        <li><%= link_to 'Terminar',finish_path %></li>
    <% end %>
  </ul> <!--
  <ul class="dropdown">
    <li><a href="">Sub1</a></li>
    <li><a href="">Sub2</a></li>
    <li class="verticallinenone"><a href="">Sub2</a></li>
    <li><a href="">Sub3</a></li>
  </ul>     -->
</div>
<%= yield %>

<div id="footermainPan">
  <div id="footerPan">
    <p class="html"><a href="http://validator.w3.org/check?uri=referer" target="_blank">html</a></p>
    <p class="css"><a href="http://jigsaw.w3.org/css-validator/check/referer" target="_blank">css</a></p>
     <ul>
      <li><%= link_to 'Home', root_path    %>|</li>
    </ul>
    <p class="copyright">©geniousweb. all right reserved.</p>
    <ul class="templateworld">
      <li>Design By:</li>
      <li><a href="http://www.templateworld.com" target="_blank">Template World</a></li>
    </ul>
  </div>
</div>
</body>
</html>

app/views/nouns/_form.html.erb
<%= form_for(@noun) do |f| %>
  <% if @noun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@noun.errors.count, "error") %> prohibited this noun from being saved:</h2>

      <ul>
      <% @noun.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">

    <%= f.label :article,"Der" %><%= f.radio_button(:article, "der") %>
    <%= f.label :article,"Das" %><%= f.radio_button(:article, "das") %>
    <%= f.label :article,"Die" %><%= f.radio_button(:article, "die") %>
  </div>





  <div class="field">
    <%= f.label :word %><br />
    <%= f.text_field :word %>
  </div>

  <div class="field">
    <%= f.label :plural %><br />
    <%= f.text_field :plural %>
  </div>
  <div class="field">
    <%= f.label :translation %><br />
    <%= f.text_field :translation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nouns/edit.html.erb
<h1>Editing noun</h1>

<%= render 'form' %>

<%= link_to 'Show', @noun %> |
<%= link_to 'Back', nouns_path %>

app/views/nouns/index.html.erb
<h1>Listing nouns</h1>

<table>
  <tr>
    <th>Article</th>
    <th>Word</th>
    <th>Plural</th>
    <th>Translation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nouns.each do |noun| %>
  <tr>
    <td><%= noun.article %></td>
    <td><%= noun.word %></td>
    <td><%= noun.plural %></td>
    <td><%= noun.translation %></td>
    <td><%= link_to 'Show', noun %></td>
    <td><%= link_to 'Edit', edit_noun_path(noun) %></td>
    <td><%= link_to 'Destroy', noun, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Noun', new_noun_path %>
     <%= link_to 'Play',play_path %>

app/views/nouns/new.html.erb
<h1>New noun</h1>

<%= render 'form' %>

<%= link_to 'Back', nouns_path %>

app/views/nouns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Word:</b>
  <%= @noun.word %>
</p>

<p>
  <b>Article:</b>
  <%= @noun.article %>
</p>

<p>
  <b>Plural:</b>
  <%= @noun.plural %>
</p>

<p>
  <b>Translation:</b>
  <%= @noun.translation %>
</p>


<%= link_to 'Edit', edit_noun_path(@noun) %> |
<%= link_to 'Back', nouns_path %>

app/views/play/_form_article.html.erb
  <%= form_tag(validation_path, :method => "post", :name => "tarjeta") do %>
     <div id="middleonePan">
       <ul class="block">
        <li><%= link_to_function "Der", "document.tarjeta['commit'].value='der'; document.tarjeta.submit()", :disabled => true %></li>
      </ul>
    </div>

      <div id="middletwoPan">
       <ul class="block">
        <li><%= link_to_function "Das", "document.tarjeta['commit'].value='das'; document.tarjeta.submit()", :disabled => true %></li>
      </ul>
    </div>

      <div id="middlethreePan">
       <ul class="block">
        <li><%= link_to_function "Die", "document.tarjeta['commit'].value='die'; document.tarjeta.submit()", :disabled => true %></li>
      </ul>
    </div>




      <%= hidden_field_tag(:commit, '') %>
              <%= hidden_field_tag(:id, @noun.id) %>
              <%= hidden_field_tag(:word, @noun.word) %>
              <%= hidden_field_tag(:article, @noun.article) %>
              <%#= hidden_field_tag(:translate, @noun.translation) %>

              <%#div id="traduccion">
                 <%#= radio_button_tag  'translation_f', @translations[0].to_s, false,
                              :onclick => "document.getElementById('der').disabled=false;
                                           document.getElementById('die').disabled=false;
                                           document.getElementById('das').disabled=false;" %>
                 <%#= label_tag @translations[0].to_s, @translations[0].to_s %>

                 <%#= radio_button_tag 'translation_f', @translations[1].to_s, false,
                              :onclick => "document.getElementById('der').disabled=false;
                                           document.getElementById('die').disabled=false;
                                           document.getElementById('das').disabled=false;" %>
                 <%#= label_tag @translations[1].to_s, @translations[1].to_s %>

                 <%#= radio_button_tag 'translation_f', @translations[2].to_s, false,
                              :onclick => "document.getElementById('der').disabled=false;
                                           document.getElementById('die').disabled=false;
                                           document.getElementById('das').disabled=false;" %>
                 <%#= label_tag @translations[1].to_s, @translations[2].to_s %>
              </div>
        <% end %>
              <%#= submit_tag("Der", :class => "button", :disabled => false, :id => "der") %>
              <%#= submit_tag("Das", :class => "button", :disabled => true, :id => "das") %>
              <%#= submit_tag("Die", :class => "button", :disabled => true, :id => "die") %>

app/views/play/_hit_article.html.erb
 <% if not @nouns_played.nil? %>
    <%= image_tag('hit.png', :size => "25x25") if @hit_article==1 %>
    <%= image_tag('fail.png', :size => "25x25") if @hit_article==0 %> Art&iacute;culo <br />

     <!--
    <%#= image_tag('hit.png', :size => "25x25") if @hit_translation==1 %>
    <%#= image_tag('fail.png', :size => "25x25") if @hit_translation==0 %> Traducci&oacute;n <br />
     -->
    <!--
        <p class="derecha">Hits Translations <%#= @hits_translation %> / <%#= @nouns_played %> </p>
    -->

<% end %>

<%# unless @word_hit.nil? %>
    <h3><%= @word_hit %></h3>
<%#end %>

app/views/play/finish.html.erb
<div id="bodytopmainPan">
  <div id="bodytopPan">
    <h2>Aciertos <%= @hits_article %> / <%= @nouns_played %></h2>
  </div>
</div>

   <!--Hits Translations <%#= @hit_translation %> / <%#= @nouns_played %></h3> -->

app/views/play/start.html.erb
<div id="bodytopmainPan">
  <div id="bodytopPan">
     <p class="hits">Aciertos: <%= @hits_article %> / <%= @nouns_played %></p>
    <h2><%= @noun.word %></h2>
  </div>
</div>
<div id="bodymainmiddlePan">
  <div id="bodymiddlePan">

        <%#= render :partial => 'hit_article' %>
        <%= render :partial => 'form_article' %>
  </div>
</div>

<!--
<p>Total Management is a <span>free, tableless, W3C-compliant</span> web design layout by Template World. This template has been tested and proven compatible with all major browser environments and operating systems. You are free to modify the design to suit your tastes in any way you like.</p>
<p class="more"><a href="http://www.free-css.com/">more</a></p>
-->

app/views/play/validation.html.erb
<div id="bodytopmainPan">
  <div id="bodytopPan">
    <h2>
      <%= image_tag('hit.png', :size => "100x100") if @hit_article==1 %>
      <%= image_tag('fail.png', :size => "100x100") if @hit_article==0 %>
    <%= @word_hit %></h2>
    <p class="more"><%= link_to 'Siguiente', next_path %></p>
  </div>
</div>